export const POST_UPLOAD_FILE_REQUEST = 'POST_UPLOAD_FILE_REQUEST';
export const POST_UPLOAD_FILE_SUCCESS = 'POST_UPLOAD_FILE_SUCCESS';
export const POST_UPLOAD_FILE_ERROR = 'POST_UPLOAD_FILE_ERROR';
