export const GET_FILM_LIST_REQUEST = 'GET_FILM_LIST_REQUEST';
export const GET_FILM_LIST_SUCCESS = 'GET_FILM_LIST_SUCCESS';
export const GET_FILM_LIST_ERROR = 'GET_FILM_LIST_ERROR';

export const DELETE_FILM_REQUEST = 'DELETE_FILM_REQUEST';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_ERROR = 'DELETE_FILM_ERROR';

export const SET_FILMS = 'SET_FILMS';
